### ISSUE TITLE
OMG the capitalization is BROKEN!!!!!1!

### ISSUE THREAD

**Issue by nusco** [robin-debry/Interactive-game#4]
Citizens,
I'm a stickler for capitalization and president of the Grammar Police. I noticed that capitalization in the following sentence is incorrect:

`you look at yourself in the mirror`

The sentence should start with an uppercase letter. I'll readily cook up a Pull Request to fix the mistake.

**Comment by robin-debry** [comment]
Thanks for your Awareness president We will fix that now.

**Comment by nusco** [comment]
I deem myself satisfied.
